name: GHAction lab7  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, test and push Docker image to ghcr.io
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.GHCR_USERNAME }}/lab7
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - 
        name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: |
            type=registry,ref=${{ vars.GHCR_USERNAME }}/lab7:cache 
          cache-to: |
            type=registry,ref=${{ vars.GHCR_USERNAME }}/lab7:cache  
          tags: ${{ steps.meta.outputs.tags }}

      - 
        name: Docker Scout CVE test
        uses: docker/scout-action@v1
        with:
          command: cve
          image: ${{ steps.build-image.outputs.digest }}
          only-severities: high

      - 
        name: Push Docker image to ghcr.io
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.GHCR_USERNAME }}/lab7:cache 
          cache-to: |
            type=registry,ref=${{ vars.GHCR_USERNAME }}/lab7:cache  
          tags: ${{ steps.meta.outputs.tags }}
